# Generated by Django 6.0.6 on 2026-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_producto_imagen_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imagen_url",
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
