# Generated by Django 6.0.6 on 2026-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_remove_producto_imagen_url_producto_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen_url",
            field=models.URLField(blank=True),
        ),
    ]
